# dataset_path: ./dataset/random_10-40_1000
# label_path: ./dataset/label/random_10-40_1000.csv
dataset_name: satisfiability
load_split_dataset: True
feature_type: all_one
task: satisfiability
graph_type: aig
task_level: graph
dataset_path: ./dataset/satisfiability

# model settings
model_settings:
  model: deepsat
  hidden_size: 128
  dropout_ratio: 0.3
  loss: binary_cross_entropy
  num_fc: 3
  num_round: 10
  dropout_ratio: 0
  mask: False
  reverse: false
  sigmoid: True
  pooling: mean

scheduler_settings:
  scheduler: ReduceLROnPlateau
  patience: 10
  factor: 0.5
  mode: min

# train settings
epochs: 100
lr: 0.0001
weight_decay: 1e-10
device: cuda:5
split_ratio: [0.6, 0.2, 0.2]
batch_size: 16

#log settings
log_file: ./log/deepsat.log

