dataset_name: test
dataset_path: ./dataset/random_10-40_1000
label_path: ./dataset/label/random_10-40_1000.csv
task_type: graph
graph_type: nsnet
feature_type: edge_type
load_field: ["label"]


model_settings:
  input_size: 4
  hidden_size: 128
  output_size: 1
  dropout_ratio: 0.3
  loss: binary_cross_entropy
  num_fc: 3
  num_round: 26
  dropout_ratio: 0

# train settings
valid_metric: acc
epochs: 2000
lr: 0.00001
weight_decay: 1e-10
device: cuda:0
split_ratio: [0.6, 0.2, 0.2]
batch_size: 16

#log settings
log_file: ./log/nsnet.log

