# dataset_path: ./dataset/random_10-40_1000
# label_path: ./dataset/label/random_10-40_1000.csv
dataset_name: neurosat
load_split_dataset: True
feature_type: all_one
task: satisfiability
# task_type: variable
# dataset_path: ./dataset/old_gms
# dataset_path: ./dataset/maxsat_test
# load_field: ["label:list"]
# dataset_path: ./dataset/is_sat_test
task_type: lcg
task_level: graph
load_field: ["label:float"]
# dataset_path: ./dataset/sr_10_40_100000
# dataset_path: ./dataset/satformer_sr_10_40_1000
# dataset_path: ./dataset/sr_10_40_10000
# dataset_path: ./dataset/my_sr_10_40_10000
dataset_path: ./dataset/my_3_sat_1000


model_settings:
  model: satformer
  input_size: 1
  hidden_size: 128
  output_size: 1
  dropout_ratio: 0
  loss: binary_cross_entropy
  num_fc: 3
  num_round: 10
  dropout_ratio: 0
  window_size: 4
  hierarchical_level: 4
  num_head: 8
  pooling: max
  is_sat_weight: 1
  unsat_core_weight: 1
  sigmoid: True

scheduler_settings:
  scheduler: ReduceLROnPlateau
  patience: 10
  factor: 0.5
  mode: min

# train settings
valid_metric: acc
epochs: 100
lr: 1e-4
weight_decay: 1e-10
device: cuda:4
split_ratio: [0.6, 0.2, 0.2]
batch_size: 32

#log settings
log_file: ./log/satformer.log

